name: Release app
on:
  push:
    branches:
      - main
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.30.0
      - name: Install dependencies
        run: pnpm i
      - name: Build application
        run: pnpm run build
      - name: 'Upload build'
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/wolbodo/website
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: wlbd
    needs:
      - publish
    steps:
      - uses: actions/checkout@master
      - name: Copy environment
        run: cp ~/config/website.env .env
      - name: Pull dependencies
        run: docker-compose pull -q
      - name: Deploy services
        run: docker-compose up -d